packages:
  - 'docs'
  - 'packages/*'

allowBuilds:
  esbuild: false # https://github.com/evanw/esbuild/issues/4085#issuecomment-2696009329
  sharp: false # https://sharp.pixelplumbing.com/install/

# Prevent installing packages published in the last <%= minimumReleaseAgeInDays %> days.
minimumReleaseAge: <%= minimumReleaseAgeInMinutes %>
